"""
Router factory for generating status operation endpoints.

Provides a factory pattern for creating router endpoints for operations that follow
the standard pattern: trigger (POST), list (GET), and status (GET/{id}).

This eliminates duplication between similar routers (downloads, decryptions) by
centralizing endpoint generation.

Usage:
    config = RouterConfig(
        operation_name="download",
        operation_name_plural="downloads",
        service_module=download_service,
        create_schema=DownloadCreate,
        response_schema=DownloadResponse,
        list_schema=DownloadList,
        id_field="download_id",
        status_values="pending, downloading, completed, failed, cancelled",
        background_task_func=BackgroundTaskService.execute_download_operation,
        creation_failure_error=ResourceNotFoundError,
    )
    factory = StatusRouterFactory(config)
    router = factory.create_router()
"""

from contextvars import ContextVar
from dataclasses import dataclass
from typing import Any, Callable, Dict, Optional, Type
from uuid import UUID

from fastapi import APIRouter, BackgroundTasks, Depends, Query, status
from loguru import logger
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from ...core.config import Config
from ...database.engine import get_db_session
from ...database.models.user import User
from ..middleware.error_handler import (
    AudioBookSyncException,
    ResourceNotFoundError,
    handle_route_errors,
)
from ..security.auth import get_current_user
from ..utils.generic_handlers import get_paginated_list

# Context variable for storing validation data between pre-flight validation and param building
_validation_context: ContextVar[Dict[str, Any]] = ContextVar("validation_context", default={})


@dataclass
class RouterConfig:
    """Configuration for a status router generated by StatusRouterFactory.

    Attributes:
        operation_name: Singular operation name (e.g., "download", "decryption")
        operation_name_plural: Plural operation name (e.g., "downloads", "decryptions")
        service_module: Service module containing business logic functions
        create_schema: Pydantic model for create request body
        response_schema: Pydantic model for operation response
        list_schema: Pydantic model for list response
        id_field: Name of the ID field (e.g., "download_id", "decryption_id")
        status_values: Comma-separated list of status values for documentation
        background_task_func: Callable to execute as background task
        creation_failure_error: Exception type to raise if creation fails
        pre_create_validator: Optional async validator called before creation
        create_status_params_builder: Optional callable to build extra params for creation
        operation_verb: Verb for operation in documentation (default: "process")
        trigger_summary: Custom summary for trigger endpoint
        list_summary: Custom summary for list endpoint
        get_status_summary: Custom summary for get status endpoint
        creation_method_name: Name of service method to create status (default: "create_{operation}_status")
        get_by_id_method_name: Name of service method to get by ID (default: "get_{operation}_by_id_for_user")
        get_items_method_name: Name of service method to get items (default: "get_{operation}s_by_user")
        count_items_method_name: Name of service method to count items (default: "count_{operation}s_by_user")
    """

    # Core identification
    operation_name: str
    operation_name_plural: str

    # Services and schemas
    service_module: Any
    create_schema: Type[BaseModel]
    response_schema: Type[BaseModel]
    list_schema: Type[BaseModel]

    # IDs
    id_field: str
    status_values: str

    # Background tasks
    background_task_func: Callable

    # Optional hooks
    pre_create_validator: Optional[Callable] = None
    create_status_params_builder: Optional[Callable] = None

    # Error handling
    creation_failure_error: Type[AudioBookSyncException] = ResourceNotFoundError

    # Documentation
    operation_verb: str = "process"
    trigger_summary: str = ""
    list_summary: str = ""
    get_status_summary: str = ""

    # Service method names
    creation_method_name: str = ""
    get_by_id_method_name: str = ""
    get_items_method_name: str = ""
    count_items_method_name: str = ""

    def __post_init__(self):
        """Set default method names based on operation name if not provided."""
        if not self.creation_method_name:
            self.creation_method_name = f"create_{self.operation_name}_status"
        if not self.get_by_id_method_name:
            self.get_by_id_method_name = f"get_{self.operation_name}_by_id_for_user"
        if not self.get_items_method_name:
            self.get_items_method_name = f"get_{self.operation_name}s_by_user"
        if not self.count_items_method_name:
            self.count_items_method_name = f"count_{self.operation_name}s_by_user"

        if not self.trigger_summary:
            self.trigger_summary = f"Trigger {self.operation_name}"
        if not self.list_summary:
            self.list_summary = f"List user's {self.operation_name_plural}"
        if not self.get_status_summary:
            self.get_status_summary = f"Get {self.operation_name} status"


class StatusRouterFactory:
    """Factory for generating status operation routers.

    Generates endpoints for operations that follow the pattern:
    - POST / : Trigger operation (create status, queue background task)
    - GET / : List operations (paginated)
    - GET /{id} : Get single operation status

    Example:
        config = RouterConfig(
            operation_name="download",
            operation_name_plural="downloads",
            service_module=download_service,
            create_schema=DownloadCreate,
            response_schema=DownloadResponse,
            list_schema=DownloadList,
            id_field="download_id",
            status_values="pending, downloading, completed, failed, cancelled",
            background_task_func=BackgroundTaskService.execute_download_operation,
        )
        factory = StatusRouterFactory(config)
        router = factory.create_router()
    """

    def __init__(self, config: RouterConfig):
        """Initialize factory with configuration.

        Args:
            config: RouterConfig instance with all required settings
        """
        self.config = config

    def create_router(self) -> APIRouter:
        """Create and return a fully configured router.

        Returns:
            APIRouter with all endpoints registered
        """
        router = APIRouter()

        # Register endpoints
        router.add_api_route(
            "/",
            self._generate_trigger_endpoint(),
            methods=["POST"],
            response_model=self.config.response_schema,
            status_code=status.HTTP_202_ACCEPTED,
            summary=self.config.trigger_summary,
            description=f"Initiate a background {self.config.operation_name} for a specific book",
            responses={
                202: {
                    "description": f"{self.config.operation_name.title()} initiated successfully"
                },
                400: {"description": "Invalid book data"},
                401: {"description": "Not authenticated"},
            },
        )

        router.add_api_route(
            "/",
            self._generate_list_endpoint(),
            methods=["GET"],
            response_model=self.config.list_schema,
            summary=self.config.list_summary,
            description=f"Get paginated list of {self.config.operation_name_plural} for the current user",
            responses={
                200: {
                    "description": f"{self.config.operation_name_plural.title()} retrieved successfully"
                },
                401: {"description": "Not authenticated"},
            },
        )

        router.add_api_route(
            f"/{{{{id_param}}}}",
            self._generate_get_status_endpoint(),
            methods=["GET"],
            response_model=self.config.response_schema,
            summary=self.config.get_status_summary,
            description=f"Get detailed status of a specific {self.config.operation_name}",
            responses={
                200: {
                    "description": f"{self.config.operation_name.title()} status retrieved successfully"
                },
                401: {"description": "Not authenticated"},
                403: {"description": "Not authorized to access this operation"},
                404: {"description": f"{self.config.operation_name.title()} not found"},
            },
        )

        return router

    def _generate_trigger_endpoint(self) -> Callable:
        """Generate trigger endpoint handler.

        Creates endpoint that:
        1. Validates request data
        2. Runs pre-flight validation if configured
        3. Creates status record in database
        4. Queues background task
        5. Returns response with status "pending"

        Returns:
            Async callable for FastAPI route handler
        """
        creation_method = getattr(self.config.service_module, self.config.creation_method_name)
        background_task_func = self.config.background_task_func
        operation_name = self.config.operation_name
        id_field = self.config.id_field
        creation_failure_error = self.config.creation_failure_error
        pre_validator = self.config.pre_create_validator
        params_builder = self.config.create_status_params_builder

        @handle_route_errors(f"trigger {operation_name}")
        async def trigger_endpoint(
            operation_data: self.config.create_schema,
            background_tasks: BackgroundTasks,
            current_user: User = Depends(get_current_user),
            db: AsyncSession = Depends(get_db_session),
        ) -> self.config.response_schema:
            logger.info(
                f"{operation_name.title()} triggered for {operation_data.asin} "
                f"by user {current_user.user_id}"
            )

            # Run pre-flight validation if configured
            if pre_validator:
                await pre_validator(operation_data, db, current_user)

            # Build creation parameters
            creation_params = {
                "db": db,
                "asin": operation_data.asin,
                "status": "pending",
            }

            # Add extra parameters if builder is configured
            if params_builder:
                extra_params = params_builder(operation_data)
                creation_params.update(extra_params)

            # Create status record
            operation = await creation_method(**creation_params)

            if not operation:
                logger.error(f"Failed to create {operation_name} record for {operation_data.asin}")
                raise creation_failure_error(
                    f"Failed to create {operation_name} record for {operation_data.asin}"
                )

            await db.commit()

            # Queue background task based on feature flag
            if Config.USE_CELERY_TASKS:
                # Enqueue Celery task
                _enqueue_celery_task(
                    operation_name=operation_name,
                    operation_id=getattr(operation, id_field),
                    user_id=str(current_user.user_id),
                    book_data=operation_data.dict(),
                )
            else:
                # Use FastAPI BackgroundTasks
                background_tasks.add_task(
                    background_task_func,
                    user_id=str(current_user.user_id),
                    **{id_field: getattr(operation, id_field)},
                    book=operation_data.dict(),
                )

            logger.info(f"{operation_name.title()} queued: {getattr(operation, id_field)}")

            # Return response
            return self.config.response_schema(
                **{
                    id_field: getattr(operation, id_field),
                    "asin": operation_data.asin,
                    "status": "pending",
                    "message": f"{operation_name.title()} initiated",
                }
            )

        return trigger_endpoint

    def _generate_list_endpoint(self) -> Callable:
        """Generate list endpoint handler.

        Creates endpoint that:
        1. Fetches paginated list from service
        2. Applies status filtering if provided
        3. Returns paginated response

        Returns:
            Async callable for FastAPI route handler
        """
        get_items_method = getattr(self.config.service_module, self.config.get_items_method_name)
        count_method = getattr(self.config.service_module, self.config.count_items_method_name)
        operation_name_plural = self.config.operation_name_plural

        @handle_route_errors(f"list {operation_name_plural}")
        async def list_endpoint(
            current_user: User = Depends(get_current_user),
            db: AsyncSession = Depends(get_db_session),
            status_filter: str = Query(
                None,
                alias="status",
                description=f"Filter by status ({self.config.status_values})",
            ),
            page: int = Query(
                default=1,
                ge=1,
                description="Page number (starting from 1)",
            ),
            page_size: int = Query(
                default=10,
                ge=1,
                le=50,
                description="Number of items per page (1-50)",
            ),
        ) -> self.config.list_schema:
            result = await get_paginated_list(
                get_items_func=get_items_method,
                response_model=self.config.response_schema,
                get_items_kwargs={
                    "db": db,
                    "user_id": str(current_user.user_id),
                    "status": status_filter,
                    "limit": page_size,
                    "offset": (page - 1) * page_size,
                },
                user_id=str(current_user.user_id),
                page=page,
                page_size=page_size,
                count_func=count_method,
                count_kwargs={
                    "db": db,
                    "user_id": str(current_user.user_id),
                    "status": status_filter,
                },
                resource_name=operation_name_plural,
            )

            return self.config.list_schema(**result)

        return list_endpoint

    def _generate_get_status_endpoint(self) -> Callable:
        """Generate get status endpoint handler.

        Creates endpoint that:
        1. Fetches single operation by ID
        2. Checks user authorization
        3. Returns operation response

        Returns:
            Async callable for FastAPI route handler
        """
        get_by_id_method = getattr(self.config.service_module, self.config.get_by_id_method_name)
        operation_name = self.config.operation_name
        id_field = self.config.id_field

        @handle_route_errors(f"get {operation_name} status")
        async def get_status_endpoint(
            id_param: str,
            current_user: User = Depends(get_current_user),
            db: AsyncSession = Depends(get_db_session),
        ) -> self.config.response_schema:
            logger.info(
                f"Fetching {operation_name} status: {id_param} " f"for user {current_user.user_id}"
            )

            # Get operation by ID with user authorization check
            operation = await get_by_id_method(
                db=db,
                **{id_field: UUID(id_param)},
                user_id=str(current_user.user_id),
            )

            if not operation:
                logger.warning(
                    f"{operation_name.title()} not found or user not authorized: {id_param}"
                )
                raise ResourceNotFoundError(f"{operation_name.title()} '{id_param}' not found")

            logger.info(f"Retrieved {operation_name} details: {id_param}")
            return self.config.response_schema.from_orm(operation)

        return get_status_endpoint


def _enqueue_celery_task(
    operation_name: str, operation_id: UUID, user_id: str, book_data: dict
) -> None:
    """
    Enqueue a Celery task based on operation name.

    Args:
        operation_name: Name of operation (download, decryption, sync)
        operation_id: ID of the operation record
        user_id: ID of the user
        book_data: Book data dictionary
    """
    # Import Celery tasks only if USE_CELERY_TASKS is enabled
    if operation_name == "download":
        from src.celery_app.tasks.download_tasks import execute_download_task

        execute_download_task.delay(
            user_id=user_id,
            download_id=str(operation_id),
            book=book_data,
        )
    elif operation_name == "decryption":
        from src.celery_app.tasks.decrypt_tasks import execute_decrypt_task

        execute_decrypt_task.delay(
            user_id=user_id,
            decryption_id=str(operation_id),
            book=book_data,
        )
    elif operation_name == "sync":
        from src.celery_app.tasks.library_tasks import execute_sync_library_task

        execute_sync_library_task.delay(
            user_id=user_id,
            sync_type=book_data.get("sync_type", "full"),
        )
    else:
        logger.warning(f"Unknown operation name for Celery: {operation_name}")
